insert into category (name) values ('Burger')
insert into category (name) values ('Sandwich')
insert into category (name) values ('Kokteyl')
insert into category (name) values ('Lavash')
insert into category (name) values ('Hot Dog')
insert into category (name) values ('Pitsa')
insert into category (name) values ('Sosiska')
insert into category (name) values ('Shaurma')
insert into category (name) values ('Free')
insert into category (name) values ('Sneik')
insert into category (name) values ('Sous')
insert into category (name) values ('Salat')
insert into category (name) values ('Suv')
